[package]
name = "accname"
description = "WAI-ARIA Accessible Name and Description Computation in Rust, generic over the document model."
keywords = ["accessibility", "a11y", "aria", "accname", "wai-aria"]
version = "0.10.1"
edition = "2021"
license.workspace = true
repository.workspace = true
rust-version = "1.85"
authors.workspace = true
categories.workspace = true

[dependencies]
a11y-dom = { workspace = true }
